### PR TITLE
Redirecting to GITHUB_ENV variable

### PR DESCRIPTION
**Pull request by cxhercules**
https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w

Updating due to advisory.

### CODE REVIEW

**Comment by cxhercules** [comment]
Tested against my secrethub repo https://github.com/dev-ops-sec-io/actions/pull/1/checks?check_run_id=1284589676

**Comment by jpcoenen** [comment]
Thank you very much for your Pull Request!

The proposed change seems to work correctly for single-line secrets, but I am not 100% sure that it also does for multi-line secrets. Looking at the new documentations for the environment variable syntax, I think we need to use the heredoc syntax to make sure secrets of multiple lines are also correctly exported.

This does introduce an interesting new challenge: what heredoc identifier can we use that is never part of a secret? For example, if we do:

```bash
echo "$var_name=<< EOF" >> $GITHUB_ENV
echo "$secret_value"
echo "EOF"
```

any secret that contains a line with `EOF` would trip up the GitHub Action. Practically it would be possible to just use a very long (random) identifier, but that would technically mean that the GitHub Action does not work for certain secrets.

I'll be doing some more investigation to see if there is a clean solution for this. If you have any suggestions, you're very welcome to share them!

**Comment by cxhercules** [comment]
Well reread again, and unless there are secrets stored that are multiline, meaning with newlines than we should be fine. I do not see that happening exactly with this, but maybe. I did try to save a document in secrethub and think it did not like it. Your prompt for secrets has you hit enter when done `[ENTER]` which introduces a newline as the delimiter so it seems to me all secrets at least at this point are one line. 

For multiple secrets it should just be:
```
echo "{name1}={value1}" >> $GITHUB_ENV
echo "{name2}={value2}" >> $GITHUB_ENV
echo "{name3}={value3}" >> $GITHUB_ENV
```

**Comment by jpcoenen** [comment]
You are very right that the default behaviour of `secrethub write` is geared towards single-line secrets. However, multiline secrets are supported. For example, by using the `--multiline` or `--in-file` flag on `secrethub write`. For example, pem-encoded private keys consist of multiple lines.

I have given it some more thought and I think we can circumvent the problem by using a long and random identifier. I have opened a PR with a suggested implementation: https://github.com/secrethub/actions/pull/20. 

This PR also contains a test that explicitly checks the Action's behaviour for multiline secrets because this was really missing.

Thank you very much for bringing this forward!

**Comment by cxhercules** [comment]
Your welcome.

**Pull request closed without merging**
